### ISSUE TITLE
Codecoverage upload fails with token error

### ISSUE THREAD

**Issue by jakoch** [hikogui/hikogui#586]
The code coverage upload fails, because it wants to have the `CODECOV_TOKEN` set, see [build log](https://github.com/hikogui/hikogui/actions/runs/6172930120/job/16754161121#step:23:80).

I was expecting that a public github repository, which uses the "free" pricing option of codecov.io
should work without a token. 

Other people run into the same issue: https://github.com/codecov/codecov-action/issues/1035

Possible solutions: 

**Set Token as Github Secret**

The secret is the CODECOV_TOKEN found in the settings page on your repository in Codecov.io.
```
uses: codecov/codecov-action@v3
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

or direct:
```
codecov -t ${CODECOV_TOKEN}
```

**Retry the upload several times**

Seems they are trying to find out, if a repository is non-private and qualifies for a non-token upload, 
but the requests to the Github API fail from time to time. Which then leads to the uploads being flaky. 
Referencing: 
- https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954/14
- https://stackoverflow.com/a/71295894/1163786

Workaround is then to simply retry the upload several times using a retry action as wrapper:
```
# retry uploading to codecov with limit to workaround flaky upload issue
- uses: wandalen/wretry.action@v1 # https://github.com/wandalen/wretry.action
    with:
      attempt_limit: 10
      uses: codecov/codecov-action@v3 # https://github.com/codecov/codecov-action
      with:
        files: ./hikogui_coverage.xml
```

I guess i send a PR with the retry workaround.
